runtime: python311
entrypoint: gunicorn famo.wsgi

service: default

env_variables:
  APPENGINE_URL: https://ali2087.uc.r.appspot.com

handlers:
  # Static files configuration
  - url: /static
    static_dir: staticfiles

  # Media files handled via Google Cloud Storage
  - url: /media
    static_dir: media  # You can use GCS to serve media if it's enabled in settings

  # Main handler for the app
  - url: /.*
    script: auto
