# Generated by Django 5.2.4 on 2025-10-24 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_lead_alter_herosection_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herosection',
            options={'verbose_name': 'Homepage Hero Section', 'verbose_name_plural': 'Homepage Hero Sections'},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
    ]
