# Generated by Django 5.2.4 on 2025-11-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_herosection_options_alter_lead_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_fi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_fi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='heading_fi',
            field=models.CharField(help_text="The main title, e.g., 'Healthy Meals, Happy Pets!'", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='subheading_fi',
            field=models.TextField(help_text='The paragraph text below the main title.', null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='subheading_secondary_fi',
            field=models.CharField(blank=True, help_text='An extra line under the main subheading, e.g., in red.', max_length=200, null=True),
        ),
    ]
