# Generated by Django 5.2.4 on 2025-12-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_onboardingslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingslide',
            name='button_text_en',
            field=models.CharField(default='Next', help_text='Button text for this slide', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='onboardingslide',
            name='button_text_fi',
            field=models.CharField(default='Next', help_text='Button text for this slide', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='onboardingslide',
            name='button_text_nl',
            field=models.CharField(default='Next', help_text='Button text for this slide', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='onboardingslide',
            name='button_text_tr',
            field=models.CharField(default='Next', help_text='Button text for this slide', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='onboardingslide',
            name='description_en',
            field=models.TextField(help_text='Slide description text', null=True),
        ),
        migrations.AddField(
            model_name='onboardingslide',
            name='description_fi',
            field=models.TextField(help_text='Slide description text', null=True),
        ),
        migrations.AddField(
            model_name='onboardingslide',
            name='description_nl',
            field=models.TextField(help_text='Slide description text', null=True),
        ),
        migrations.AddField(
            model_name='onboardingslide',
            name='description_tr',
            field=models.TextField(help_text='Slide description text', null=True),
        ),
        migrations.AddField(
            model_name='onboardingslide',
            name='title_en',
            field=models.CharField(help_text='Slide title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='onboardingslide',
            name='title_fi',
            field=models.CharField(help_text='Slide title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='onboardingslide',
            name='title_nl',
            field=models.CharField(help_text='Slide title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='onboardingslide',
            name='title_tr',
            field=models.CharField(help_text='Slide title', max_length=200, null=True),
        ),
    ]
