# Generated by Django 5.2.4 on 2025-12-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_faq_answer_fi_faq_question_fi_herosection_heading_fi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Slide title', max_length=200)),
                ('title_en', models.CharField(help_text='Slide title', max_length=200, null=True)),
                ('title_tr', models.CharField(help_text='Slide title', max_length=200, null=True)),
                ('title_nl', models.CharField(help_text='Slide title', max_length=200, null=True)),
                ('title_fi', models.CharField(help_text='Slide title', max_length=200, null=True)),
                ('description', models.TextField(help_text='Slide description text')),
                ('description_en', models.TextField(help_text='Slide description text', null=True)),
                ('description_tr', models.TextField(help_text='Slide description text', null=True)),
                ('description_nl', models.TextField(help_text='Slide description text', null=True)),
                ('description_fi', models.TextField(help_text='Slide description text', null=True)),
                ('icon', models.ImageField(help_text='Icon/image for the slide. Recommended size: 200x200px.', upload_to='onboarding_icons/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this slide in the app')),
                ('button_text', models.CharField(default='Next', help_text='Button text for this slide', max_length=50)),
                ('button_text_en', models.CharField(default='Next', help_text='Button text for this slide', max_length=50, null=True)),
                ('button_text_tr', models.CharField(default='Next', help_text='Button text for this slide', max_length=50, null=True)),
                ('button_text_nl', models.CharField(default='Next', help_text='Button text for this slide', max_length=50, null=True)),
                ('button_text_fi', models.CharField(default='Next', help_text='Button text for this slide', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Onboarding Slide',
                'verbose_name_plural': 'Onboarding Slides',
                'ordering': ['order'],
            },
        ),
    ]
