# Generated by Django 5.2.4 on 2025-12-31 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_legaldocument_consentlog_clinicconsent_userconsent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('APPOINTMENT_CONFIRMED', 'Appointment Confirmed'), ('APPOINTMENT_CANCELLED', 'Appointment Cancelled'), ('APPOINTMENT_REMINDER', 'Appointment Reminder'), ('NEW_APPOINTMENT', 'New Appointment'), ('EMAIL_CONFIRMATION', 'Email Confirmation Needed'), ('ACCOUNT_VERIFIED', 'Account Verified'), ('ADMIN_MESSAGE', 'Message from Admin'), ('SYSTEM', 'System Notification'), ('PET_REMINDER', 'Pet Care Reminder'), ('NEW_REFERRAL', 'New Referral')], default='SYSTEM', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, help_text='URL to redirect when notification is clicked', max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_important', models.BooleanField(default=False, help_text='Important notifications appear at the top')),
                ('action_required', models.BooleanField(default=False, help_text='Notification requires user action')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_by', models.ForeignKey(blank=True, help_text='Admin who sent this notification (for admin messages)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Notification',
                'verbose_name_plural': 'User Notifications',
                'ordering': ['-is_important', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='core_userno_user_id_4636e4_idx'), models.Index(fields=['user', 'created_at'], name='core_userno_user_id_ed0b1c_idx'), models.Index(fields=['notification_type'], name='core_userno_notific_a0d5c0_idx')],
            },
        ),
    ]
