# Generated by Django 5.2.4 on 2026-01-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_devicetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='VeterinarySectionAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Veterinary Professional', help_text='Label used in the admin list.', max_length=150)),
                ('image', models.ImageField(help_text='Image shown on the Veterinary Professional section. Recommended 800x800px.', upload_to='vet_section/')),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for the image.', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Only one asset will be used on the homepage at a time.')),
            ],
            options={
                'verbose_name': 'Veterinary Section Asset',
                'verbose_name_plural': 'Veterinary Section Assets',
            },
        ),
    ]
