# Generated by Django 5.2.4 on 2025-08-15 14:07

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, default=''),
        ),
    ]
