# Generated by Django 5.2.4 on 2025-08-02 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0018_activitylevel_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylevel',
            name='icon',
        ),
    ]
