# Generated by Django 5.2.4 on 2026-02-23 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0022_migrate_translations'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetAgeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('age_months_at_start', models.PositiveIntegerField(help_text="Pet's age in months when this category started")),
                ('transition_reason', models.CharField(default='manual_entry', help_text='Reason for this age category assignment', max_length=100)),
                ('age_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.agecategory')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_history', to='pet.pet')),
            ],
            options={
                'verbose_name': 'Pet Age History',
                'verbose_name_plural': 'Pet Age Histories',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PetConditionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('food_allergy_other', models.CharField(blank=True, max_length=255, null=True)),
                ('snapshot_date', models.DateTimeField(auto_now_add=True)),
                ('transition_reason', models.CharField(default='age_progression', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this snapshot')),
                ('activity_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pet.activitylevel')),
                ('age_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.agecategory')),
                ('body_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pet.bodytype')),
                ('food_feeling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pet.foodfeeling')),
                ('food_importance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pet.foodimportance')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_snapshots', to='pet.pet')),
                ('treat_frequency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pet.treatfrequency')),
            ],
            options={
                'verbose_name': 'Pet Condition Snapshot',
                'verbose_name_plural': 'Pet Condition Snapshots',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='AgeTransitionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transition_age_months', models.PositiveIntegerField(help_text='Age in months when transition occurs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_from', to='pet.agecategory')),
                ('pet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_transition_rules', to='pet.pettype')),
                ('to_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_to', to='pet.agecategory')),
            ],
            options={
                'ordering': ['pet_type', 'transition_age_months'],
                'unique_together': {('pet_type', 'from_category', 'to_category')},
            },
        ),
        migrations.CreateModel(
            name='PetConditionSnapshotFoodAllergies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('food_allergy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.foodallergy')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_allergy_snapshots', to='pet.petconditionsnapshot')),
            ],
            options={
                'unique_together': {('snapshot', 'food_allergy')},
            },
        ),
        migrations.CreateModel(
            name='PetConditionSnapshotFoodTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('food_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.foodtype')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_type_snapshots', to='pet.petconditionsnapshot')),
            ],
            options={
                'unique_together': {('snapshot', 'food_type')},
            },
        ),
        migrations.CreateModel(
            name='PetConditionSnapshotHealthIssues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('health_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.healthissue')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_issue_snapshots', to='pet.petconditionsnapshot')),
            ],
            options={
                'unique_together': {('snapshot', 'health_issue')},
            },
        ),
    ]
