# Generated by Django 5.2.4 on 2025-12-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0023_pet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylevel',
            name='description_en',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activitylevel',
            name='description_fi',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activitylevel',
            name='description_nl',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activitylevel',
            name='description_tr',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activitylevel',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='activitylevel',
            name='name_fi',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='activitylevel',
            name='name_nl',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='activitylevel',
            name='name_tr',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='agecategory',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agecategory',
            name='name_fi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agecategory',
            name='name_nl',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agecategory',
            name='name_tr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bodytype',
            name='description_en',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bodytype',
            name='description_fi',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bodytype',
            name='description_nl',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bodytype',
            name='description_tr',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bodytype',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bodytype',
            name='name_fi',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bodytype',
            name='name_nl',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bodytype',
            name='name_tr',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='breed',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='breed',
            name='name_fi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='breed',
            name='name_nl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='breed',
            name='name_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='foodallergy',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='foodallergy',
            name='name_fi',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='foodallergy',
            name='name_nl',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='foodallergy',
            name='name_tr',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='foodfeeling',
            name='description_en',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='foodfeeling',
            name='description_fi',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='foodfeeling',
            name='description_nl',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='foodfeeling',
            name='description_tr',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='foodfeeling',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='foodfeeling',
            name='name_fi',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='foodfeeling',
            name='name_nl',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='foodfeeling',
            name='name_tr',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='foodimportance',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='foodimportance',
            name='name_fi',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='foodimportance',
            name='name_nl',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='foodimportance',
            name='name_tr',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='name_fi',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='name_nl',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='name_tr',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='gender',
            name='name_en',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='gender',
            name='name_fi',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='gender',
            name='name_nl',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='gender',
            name='name_tr',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='healthissue',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='healthissue',
            name='name_fi',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='healthissue',
            name='name_nl',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='healthissue',
            name='name_tr',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pettype',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pettype',
            name='name_fi',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pettype',
            name='name_nl',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pettype',
            name='name_tr',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='treatfrequency',
            name='description_en',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='treatfrequency',
            name='description_fi',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='treatfrequency',
            name='description_nl',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='treatfrequency',
            name='description_tr',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='treatfrequency',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='treatfrequency',
            name='name_fi',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='treatfrequency',
            name='name_nl',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='treatfrequency',
            name='name_tr',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
