# Generated by Django 5.2.4 on 2026-02-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0023_petagehistory_petconditionsnapshot_agetransitionrule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='age_at_registration_months',
            field=models.PositiveIntegerField(blank=True, help_text="Pet's age in months at registration", null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='age_at_registration_weeks',
            field=models.PositiveIntegerField(blank=True, help_text="Pet's age in weeks at registration", null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='age_at_registration_years',
            field=models.PositiveIntegerField(blank=True, help_text="Pet's age in years at registration", null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, help_text='When the pet profile was created', null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Calculated birth date based on age at registration', null=True),
        ),
    ]
