# Generated by Django 5.2.4 on 2026-02-23 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0024_add_registration_age_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='current_age_months',
            field=models.PositiveIntegerField(blank=True, help_text='Current age in months (auto-calculated)', null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='current_age_weeks',
            field=models.PositiveIntegerField(blank=True, help_text='Current age in weeks (auto-calculated)', null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='current_age_years',
            field=models.PositiveIntegerField(blank=True, help_text='Current age in years (auto-calculated)', null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age_months',
            field=models.PositiveIntegerField(blank=True, help_text="Pet's age in months at registration (editable)", null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age_weeks',
            field=models.PositiveIntegerField(blank=True, help_text="Pet's age in weeks at registration (editable)", null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age_years',
            field=models.PositiveIntegerField(blank=True, help_text="Pet's age in years at registration (editable)", null=True),
        ),
    ]
