# Generated by Django 5.2.4 on 2026-03-08 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0025_add_current_age_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetWeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=2, help_text='Weight in kilograms', max_digits=5)),
                ('recorded_at', models.DateField(help_text='Date when the weight was recorded')),
                ('note', models.CharField(blank=True, help_text='Optional note about this weight record', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_records', to='pet.pet')),
            ],
            options={
                'verbose_name': 'Pet Weight Record',
                'verbose_name_plural': 'Pet Weight Records',
                'ordering': ['-recorded_at', '-created_at'],
            },
        ),
    ]
