# Generated by Django 5.2.4 on 2026-03-08 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0026_petweightrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetDataChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Name of the field that changed', max_length=100)),
                ('old_value', models.TextField(blank=True, help_text='Previous value (JSON for complex fields)', null=True)),
                ('new_value', models.TextField(blank=True, help_text='New value (JSON for complex fields)', null=True)),
                ('change_reason', models.CharField(choices=[('user_update', 'User Update'), ('age_transition', 'Age Category Transition'), ('weight_entry', 'Weight Record Entry'), ('system_recalculation', 'System Recalculation'), ('admin_update', 'Admin Update')], default='user_update', help_text='Reason for the change', max_length=100)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who made the change', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_changes', to='pet.pet')),
            ],
            options={
                'verbose_name': 'Pet Data Change Log',
                'verbose_name_plural': 'Pet Data Change Logs',
                'ordering': ['-changed_at'],
            },
        ),
    ]
