# Generated by Django 5.2.4 on 2026-04-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional photo (will be compressed to under 1 MB automatically)', null=True, upload_to='forum/questions/'),
        ),
    ]
