# Generated by AI assistant for adding structured JSON fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aihub', '0002_aihealthreport_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airecommendation',
            name='content_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aihealthreport',
            name='summary_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
