# Generated by Django 5.2.4 on 2025-11-19 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vets', '0003_clinic_latitude_clinic_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('is_closed', models.BooleanField(default=False, help_text='Clinic is closed on this day')),
                ('open_time', models.TimeField(blank=True, help_text='Opening time', null=True)),
                ('close_time', models.TimeField(blank=True, help_text='Closing time', null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours_schedule', to='vets.clinic')),
            ],
            options={
                'verbose_name_plural': 'Working hours',
                'ordering': ['day_of_week'],
                'unique_together': {('clinic', 'day_of_week')},
            },
        ),
    ]
