# Generated by Django 5.2.4 on 2025-11-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vets', '0004_workinghours'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='clinic_eoi',
            field=models.BooleanField(default=False, help_text="Indicates whether the clinic has expressed interest in participating in FAMMO's pilot program."),
        ),
    ]
