# Generated by Django 5.2.4 on 2025-12-31 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0025_migrate_translations'),
        ('vets', '0005_clinic_clinic_eoi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls display order')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Appointment Reason',
                'verbose_name_plural': 'Appointment Reasons',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_date', models.DateField(db_index=True, help_text='The date of the appointment')),
                ('appointment_time', models.TimeField(help_text='The time of the appointment')),
                ('duration_minutes', models.PositiveIntegerField(default=30, help_text='Expected duration in minutes')),
                ('reason_text', models.CharField(blank=True, help_text='Custom reason or additional details', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Additional notes from the user')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED_USER', 'Cancelled by User'), ('CANCELLED_CLINIC', 'Cancelled by Clinic'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No Show')], db_index=True, default='PENDING', max_length=20)),
                ('clinic_notified_at', models.DateTimeField(blank=True, help_text='When the clinic was notified', null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When the clinic confirmed the appointment', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When the appointment was cancelled', null=True)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation')),
                ('reference_code', models.CharField(blank=True, help_text='Unique reference code for the appointment', max_length=20, unique=True)),
                ('clinic', models.ForeignKey(help_text='The clinic where the appointment is booked', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='vets.clinic')),
                ('pet', models.ForeignKey(help_text='The pet for this appointment', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='pet.pet')),
                ('user', models.ForeignKey(help_text='The user who booked the appointment', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('reason', models.ForeignKey(blank=True, help_text='Predefined reason for the appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='vets.appointmentreason')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['-appointment_date', '-appointment_time'],
            },
        ),
        migrations.CreateModel(
            name='ClinicNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('NEW_APPOINTMENT', 'New Appointment'), ('CANCELLED_APPOINTMENT', 'Cancelled Appointment'), ('APPOINTMENT_REMINDER', 'Appointment Reminder'), ('REFERRAL', 'New Referral'), ('SYSTEM', 'System Notification')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='vets.appointment')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='vets.clinic')),
            ],
            options={
                'verbose_name': 'Clinic Notification',
                'verbose_name_plural': 'Clinic Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['clinic', 'appointment_date'], name='vets_appoin_clinic__d867e0_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['user', 'appointment_date'], name='vets_appoin_user_id_239d31_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'appointment_date'], name='vets_appoin_status_ffdbb8_idx'),
        ),
    ]
