# Generated by Django 5.2.4 on 2025-11-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_profile_latitude_profile_location_consent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Türkçe'), ('nl', 'Nederlands'), ('fi', 'Suomi')], default='en', help_text="User's preferred language for the mobile app", max_length=7, verbose_name='Preferred Language'),
        ),
    ]
