# Generated by Django 5.2.4 on 2025-12-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vets', '0006_add_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentreason',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentreason',
            name='description_fi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentreason',
            name='description_nl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentreason',
            name='description_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentreason',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='appointmentreason',
            name='name_fi',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='appointmentreason',
            name='name_nl',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='appointmentreason',
            name='name_tr',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
