# Generated by Django 5.2.4 on 2025-12-19 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpost_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('tr', 'Turkish'), ('fi', 'Finnish')], default='en', max_length=5)),
                ('primary_keyword', models.CharField(blank=True, max_length=100)),
                ('secondary_keywords', models.TextField(blank=True, help_text='Comma-separated keywords')),
                ('target_audience', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Additional instructions for AI generation')),
                ('status', models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped')], default='TODO', max_length=20)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority topics are picked first')),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Topic',
                'verbose_name_plural': 'Blog Topics',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Turkish'), ('fi', 'Finnish')], default='en', max_length=5),
        ),
        migrations.CreateModel(
            name='BlogPostImageSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('THUMBNAIL', 'Thumbnail'), ('INLINE', 'Inline')], max_length=20)),
                ('alt_text', models.CharField(max_length=200)),
                ('prompt', models.TextField(help_text='AI image generation prompt')),
                ('placement_hint', models.CharField(blank=True, help_text='Where to place the image in the post', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_suggestions', to='blog.blogpost')),
            ],
            options={
                'verbose_name': 'Blog Post Image Suggestion',
                'verbose_name_plural': 'Blog Post Image Suggestions',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogGenerationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('tr', 'Turkish'), ('fi', 'Finnish')], default='en', max_length=5)),
                ('tone', models.CharField(choices=[('professional', 'Professional'), ('casual', 'Casual'), ('friendly', 'Friendly'), ('authoritative', 'Authoritative')], default='professional', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATED', 'Generated'), ('FAILED', 'Failed'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published')], default='PENDING', max_length=20)),
                ('generated_json', models.JSONField(blank=True, help_text='Full JSON response from AI', null=True)),
                ('linkedin_draft', models.TextField(blank=True, help_text='LinkedIn post draft (600-1200 chars)')),
                ('x_draft', models.TextField(blank=True, help_text='X/Twitter post draft (<=280 chars)')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_request', to='blog.blogpost')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_requests', to='blog.blogtopic')),
            ],
            options={
                'verbose_name': 'Blog Generation Request',
                'verbose_name_plural': 'Blog Generation Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
