# Generated by Django 5.2.4 on 2025-12-12 15:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_onboardingslide'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('user_terms', 'User Terms and Conditions'), ('user_privacy', 'User Privacy Policy'), ('clinic_terms', 'Clinic Terms and Conditions'), ('clinic_partnership', 'Clinic Partnership Agreement'), ('clinic_eoi', 'Expression of Interest (EOI) Terms')], help_text='Type of legal document', max_length=50)),
                ('title', models.CharField(help_text="Document title (e.g., 'Terms and Conditions v2.0')", max_length=255)),
                ('title_en', models.CharField(help_text="Document title (e.g., 'Terms and Conditions v2.0')", max_length=255, null=True)),
                ('title_tr', models.CharField(help_text="Document title (e.g., 'Terms and Conditions v2.0')", max_length=255, null=True)),
                ('title_nl', models.CharField(help_text="Document title (e.g., 'Terms and Conditions v2.0')", max_length=255, null=True)),
                ('title_fi', models.CharField(help_text="Document title (e.g., 'Terms and Conditions v2.0')", max_length=255, null=True)),
                ('version', models.CharField(help_text="Version identifier (e.g., '1.0', '2.1', 'v2021-11-01')", max_length=20)),
                ('content', models.TextField(help_text='Full legal document content (HTML allowed)')),
                ('content_en', models.TextField(help_text='Full legal document content (HTML allowed)', null=True)),
                ('content_tr', models.TextField(help_text='Full legal document content (HTML allowed)', null=True)),
                ('content_nl', models.TextField(help_text='Full legal document content (HTML allowed)', null=True)),
                ('content_fi', models.TextField(help_text='Full legal document content (HTML allowed)', null=True)),
                ('summary', models.TextField(blank=True, help_text='Brief summary of document (optional)')),
                ('summary_en', models.TextField(blank=True, help_text='Brief summary of document (optional)', null=True)),
                ('summary_tr', models.TextField(blank=True, help_text='Brief summary of document (optional)', null=True)),
                ('summary_nl', models.TextField(blank=True, help_text='Brief summary of document (optional)', null=True)),
                ('summary_fi', models.TextField(blank=True, help_text='Brief summary of document (optional)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this the active version? Only one version per doc_type/language should be active')),
                ('effective_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When this version becomes effective')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes about changes')),
            ],
            options={
                'verbose_name': 'Legal Document',
                'verbose_name_plural': 'Legal Documents',
                'ordering': ['-effective_date'],
                'indexes': [models.Index(fields=['doc_type', 'is_active'], name='core_legald_doc_typ_be5bf5_idx'), models.Index(fields=['doc_type', 'effective_date'], name='core_legald_doc_typ_bf6c61_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('doc_type',), name='unique_active_doc_per_type')],
            },
        ),
        migrations.CreateModel(
            name='ConsentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Document Created'), ('updated', 'Document Updated'), ('accepted', 'Consent Accepted'), ('revoked', 'Consent Revoked'), ('reminded', 'User Reminded')], max_length=20)),
                ('details', models.TextField(blank=True, help_text='Additional information about the action')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_log_actions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_logs', to='core.legaldocument')),
            ],
            options={
                'verbose_name': 'Consent Log',
                'verbose_name_plural': 'Consent Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['document', 'timestamp'], name='core_consen_documen_7080a2_idx'), models.Index(fields=['user', 'timestamp'], name='core_consen_user_id_d0481f_idx'), models.Index(fields=['action', 'timestamp'], name='core_consen_action_5e16f0_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClinicConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_email', models.EmailField(help_text='Email of clinic being registered (for audit trail)', max_length=254)),
                ('accepted', models.BooleanField(default=True, help_text='Whether clinic accepted (true) or revoked (false)')),
                ('accepted_at', models.DateTimeField(auto_now_add=True, help_text='When consent was given')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address when consent was given', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent (browser info) when consent was given')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_legal_consents', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(help_text='The legal document accepted', on_delete=django.db.models.deletion.PROTECT, to='core.legaldocument')),
            ],
            options={
                'verbose_name': 'Clinic Consent',
                'verbose_name_plural': 'Clinic Consents',
                'ordering': ['-accepted_at'],
                'indexes': [models.Index(fields=['user', 'accepted_at'], name='core_clinic_user_id_953a17_idx'), models.Index(fields=['document', 'accepted_at'], name='core_clinic_documen_e3081c_idx'), models.Index(fields=['clinic_email', 'accepted_at'], name='core_clinic_clinic__e3f3ee_idx')],
                'unique_together': {('user', 'document', 'clinic_email')},
            },
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=True, help_text='Whether user accepted (true) or revoked (false)')),
                ('accepted_at', models.DateTimeField(auto_now_add=True, help_text='When consent was given')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address when consent was given', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent (browser info) when consent was given')),
                ('document', models.ForeignKey(help_text='The legal document accepted', on_delete=django.db.models.deletion.PROTECT, to='core.legaldocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Consent',
                'verbose_name_plural': 'User Consents',
                'ordering': ['-accepted_at'],
                'indexes': [models.Index(fields=['user', 'accepted_at'], name='core_userco_user_id_69c4b8_idx'), models.Index(fields=['document', 'accepted_at'], name='core_userco_documen_90fbea_idx')],
                'unique_together': {('user', 'document')},
            },
        ),
    ]
