# Generated by Django 5.2.4 on 2025-08-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0016_alter_activitylevel_options_activitylevel_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodallergy',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='healthissue',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='foodallergy',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='healthissue',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
