# Generated by Django 5.2.4 on 2025-08-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0017_alter_foodallergy_options_alter_healthissue_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylevel',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='activity_icons/'),
        ),
    ]
