# Generated by Django 5.2.4 on 2025-12-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0022_pet_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pet_images/'),
        ),
    ]
