# Generated by Django 5.2.4 on 2026-03-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogtopic_blogpost_is_published_blogpost_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Alternative text for the thumbnail image (improves accessibility and SEO)', max_length=200, null=True),
        ),
    ]
