# Generated by Django 5.2.4 on 2025-12-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogtopic_blogpost_is_published_blogpost_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloggenerationrequest',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Türkçe'), ('nl', 'Nederlands'), ('fi', 'Suomi')], default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Türkçe'), ('nl', 'Nederlands'), ('fi', 'Suomi')], default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='blogtopic',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Türkçe'), ('nl', 'Nederlands'), ('fi', 'Suomi')], default='en', max_length=5),
        ),
    ]
