# Generated by Django 5.2.4 on 2026-05-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_add_image_alt_to_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL for this post. Use to prevent duplicate-content penalties when the same content lives at multiple URLs.', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Dedicated image for social media sharing (Open Graph / Twitter Card). Falls back to the main thumbnail if empty.', null=True, upload_to='blog_og_images/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Custom page title for Google search results (max 60 chars). Falls back to post title if empty.', max_length=60, null=True),
        ),
    ]
