# Generated by Django - Placeholder migration to match cPanel
# This migration exists on cPanel production server

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vets', '0005_clinic_clinic_eoi'),
    ]

    operations = [
        # This migration was created directly on cPanel
        # The actual operations are already applied to the production database
        # This is a placeholder to maintain migration history consistency
    ]