# Generated by Django 5.2.4 on 2025-12-16 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_profile_preferred_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, help_text='Optional reason for deletion')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved - Awaiting Deletion'), ('cancelled', 'Cancelled by User'), ('completed', 'Deletion Completed')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('scheduled_deletion_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('had_pets', models.BooleanField(default=False)),
                ('had_clinic', models.BooleanField(default=False)),
                ('pets_count', models.IntegerField(default=0)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_deletions', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Deletion Request',
                'verbose_name_plural': 'Account Deletion Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
