# Generated by Django 5.2.4 on 2025-12-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionPredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source', models.CharField(default='api', help_text="Source of the prediction request (e.g., 'mobile', 'web', 'api')", max_length=50)),
                ('backend', models.CharField(db_index=True, default='openai', help_text="AI backend used (e.g., 'openai', 'proprietary', 'mock')", max_length=50)),
                ('model_version', models.CharField(blank=True, db_index=True, help_text='Version of the AI model that generated the prediction', max_length=100)),
                ('species', models.CharField(db_index=True, max_length=20)),
                ('life_stage', models.CharField(blank=True, db_index=True, max_length=20)),
                ('breed_size_category', models.CharField(blank=True, max_length=20)),
                ('health_goal', models.CharField(blank=True, db_index=True, max_length=50)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('age_years', models.FloatField(blank=True, null=True)),
                ('body_condition_score', models.IntegerField(blank=True, null=True)),
                ('input_payload', models.JSONField(help_text='Complete validated pet profile input as JSON')),
                ('output_payload', models.JSONField(help_text='Complete AI prediction output as JSON')),
                ('notes', models.TextField(blank=True, help_text='Optional notes for manual annotation or quality assessment', null=True)),
            ],
            options={
                'verbose_name': 'Nutrition Prediction Log',
                'verbose_name_plural': 'Nutrition Prediction Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'species'], name='ai_core_nut_created_bb533d_idx'), models.Index(fields=['backend', 'model_version'], name='ai_core_nut_backend_e2bd62_idx')],
            },
        ),
    ]
